apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBEWCSjZGkh3owyfvSPvSGSnE/F7JMBziMviCvK3J4ave6uJTCq3HPlLwXO6SQkieN9PfbDG0PwTrcL4WOM4AyH7Igckn1dyGMTI3OjWpbnBHJILLeqWIw42fMYKhKXoKQqblRa0+BrSheRmYF+STMkEU7Ua3JWROh5BCFhHPxlzmK1sWI57Q/bLM9oEap2PJtfvIof0snDaAcvL/Kb9mSaw7KzaY09ir5XhqueIb875HAQ32uQk3uVrAeVYf4P4MxEEp+jmw1XMyewm/OQQR23MJTZslyEqFkr/AwwOskPSowOoOIoM8Y4QtEiCvOLq2AiziJqdlfkFLFW8K6mJ7qoj29QD72NpjNIxVYpgRIEGIq0DmeVvfLI7LHG9CXM6qUi6wNI0YfzUKDxjerywPMqznjHg88Q3UHrpRdi6rSxTYFB6/WXqZXWjH2CECl/g0C8/TV+kGBxK8aLmWo+rB67NRUDIVJZT6xwb0tu06s1nZGeuLTtbsiFmFumPPw6Sr72tZ6yF7qhRVd8vDyO6PIwe/lPCfGCh4p5nx9W8+zolUjsCN8TJrMUAR+M3K5ez2UylUslK4mOz+CO4ZIL7toK/dE3k4SAAprqG9CZrpoXOLkpCBzLk/rhQ6wc1GuJMJE1wZtGo+RE0CW+552GU7JaTsn3uczAykaDkfcmbE5ZAr5JA5BJB3DaJ3d5zxY+oayt2Lrk4l9ldnv1
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring

