apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgCnXw/4T371vFxRohB+6+cO6g/nDzrBoktYusqGeR13yQ7IE6eucrTU4ZCXTtucbK9+5+ZUmIOVm52BylKDPswxjKuzsb/WchBGU5V532ygQh8vrtMI9v85vE+vzLDP0ozU3q4FGd9oXNR2CUOwHZyEznhhp6Ky+UAm2+ZHTwd8V+TVZ87p8XluoJQcd28+fkXnfEdC43hwHNf9X5DhImxA2Exiz95ymT9kUuybDMR2YQpiHrEdZZ9hUK29FaluQt7UI/iKubVKLkBkDNJeyFFr1GzKRyd/qwfhbgmbK2NsZGgJ08O2t54A4oP7VpygOKyR1Ysw2geVT/yhzfu6l6B7+tX9+cvSHGT+1xbYWMFivcgUgnEpwHNnGnaY8CVCSq22ppMlnAvnWujB5p9GQKRR6QufhyGq0CHs0sHwbmxT0OL5YVX22vRUWiFtgxWt+uomLesB87YiaS8Eugtt+SzQlzUPUYw9ELymekiIkyYyn4mgO1K28mfLuJGGoq3gSLEh/stU4AR6AiiTGFPbxzS1dCD9Nv/x4Zyk3vB9O5v3mSbkE3uEd7eZsq65L5htQpCDiHPLSyUqz46CzRAkQO9UvVUYSKdMAV0VfUHq8z/aUHZrr89LukO/gTANpCxgqJUYQ5sIPfJw+Cr0/VqRPzWcEaAyjJwB5A54v1dy6efsoYoazOkM1LhoC4HDcLuaj6mJau1W9dg5nePl
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring

