apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgCaxFPqjH/5GHJigeC2WW1Q76cxOQ5U//+A8ZdCx/xweWk9uvnqpT18M5f2uulWPcP1cb5ghO5hMixo9WXQxh4WOWvn9ZuRGj+zrPSs9Di+nmK+el9ECT+9Og4YGEnYsc8yUa/Ib6s70eE2xUgw0pngjngjNZOGbMwmDKRXI6FXRDiAi9BOnZqCVTwm1ycA9qdaeqGIOCm3vh5fBEJIS/V/iRlZzHo4HDP3MxymqDpbNIT1bm1a4yMH/+mNdI2y7reeDENe/OgWhblWslLsg1F66QkI6dLdKj5+R8tJg0m6Qlggk/FrFziqTWOP+ChdnS05BNU9Z2SrMe6xWWGeKH/pBClaavRUG+E5NPNKSMl4vCssZFt8cl5+IFTEPZT1rej8UHFL/G0D07LLVYvdKOAn798/XgVGdn0jerpWNyDaaUTrtKK23STiBddDJP62rElBl8W2Lm1PyNKR5JbCzf8N8lJxWp46+/WtmY5Ds6MQojkrcfrZ1kPc9bYUCC8rU4s7MQYyhuPM7ea+G9KdKIJKZFjubCc3t2UzxuMBHvALdy3T7y5705hamIGzOuIQCEWzDNlSwum3DqNz8wST4iVmJXWj4TzyACFJc+5Im0ioyaGkldy7RmwCmg5A241y49al/kbD0YG97xWT0FRO+qmKF4zaRGrCer53MRW73ZzwkWrRyr//HCtuMBWfczpMgfuCQzHQu+MmAR9i
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring

