apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBlnaVtBeoBXp55asw4QBbwVTZhBIDhlsG1n0FP8gWB/V+8Zz6TIj+pf2WotBjtTccln/Nmht6FmKDRqsGO7uPPG1wuVkV/soswp9FTsrmA8QZwJ6Do9baTiEAzzr0wSZL3R5y8E3MzRV6LWBU17jmZ/WcJo+N4cDr6hRxbsh9dAcX3N82RNK8aMPsJTBORHlAS/HI9PBEX4V1oz+iinUBPE+FzXSqnuBL4qxpPHwTL9PMF8nyQU79NvaU5NL4LX4pUoUIwvOmboun7kKIqiEeP6FM7OQFrXb4FW3Q8OIye/ETp+gUqArKx0O9VeUJl66cf7aHDBX5I4wgzAiKByGGi3r77wQ3u3VERSE3WBejKcR/JyBuzuHBg0YHlszqNWFLU2ZHJFv0ELm9QHdTsQeS3nGFWfLeRvg1IrUky7INkixt9VJz8JJgvWmffzHeYEjBMCoIugkY5XLYE4Dqe45MrRcifqWEo/3+ItwAEy8zNu3QboxNc08tFGuhpXpGWeS6s3Vj7kP+Q8k9251Mpej47LRgEE3WibUR+sscHHLDEInhHAViVx19PrMp2q2XFTUXZIq2GrcWf3od0qGxCr1KPqXjW8cmJX8HnWPuXkwZz33QTaCxF5qjBJiR0FKK1kQzosVwVhkQP/YPvVXMiV4eAT/aLfj+tz6vQI66v+EbJ0l+ndAQ77ZbM311Hi4XlIobAcNCaEqysgPWz
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring

