---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
  encryptedData: