apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgAlVi12H5cRjcoGaQMCJgynZqQRRd2Sz49dj08dAlmIaKI+QLeql1ILzkUbnCwEeDiEYiW5UQWld4uM/hKXjiDOj7GGKbCXj7+KA/JQTTyafwheUvD4UerCjPG8cp+LM4r8Qg5I034iZ/37176xj/b6hs7GiCKFkzYRSo7e354pr7V/vQGYkJGWXIE9Pwp4FYt1+AoKNqvnifyFJN6EfzyyUXpXprzYmN8kuNz16lSV9AqQL1AeYIcJbwMwKIIerhafih6Ie5kK27bcy7ORmr2MDfdc77gi/0N6gCBHjlSol6ND0j/hNyvAgFh2LxdLwqSnab9Hu6Vdtu7M9dzgFB5SMBiD2FeVFOezmUZTe45wO73/IbY/aWwDXMGWhpupXenBebOSOFBwJw/UWVRRG2voX3wM/teQUbLe7P2YQJ2PWEkyzwOZZwBi0bSlrOtZq8Gz7navtIXiZIfkSwESixZstwiqu6Tec9MQkPswh9sSlmVWXGJByWhOBw79xHoHL1fzAt5UpFFe26gxyTSo4oWR4o8zE3Few+dz64piJBe35VtDaF8trra5+G3H8dWLoG+QOU/wFoHVQfWO2Xbu0GVQMRps4NTfyH+Dp+4n3W4aL1+D+OcpVlevCg6pM5qYlVK1DGsNH60tBAvSRrB6cPdvdJAXNiWRQYtlEUIq5fk/UBedUOd8OiUgwT/9C009+MM=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring

