---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
  encryptedData:
    password: AgCIhcMlduCLonzRts2I2sP8MYPBGlsHQuQtD5tnLiIehjIOqvHCnuN1sxljXIw/FyRqqj/gzRbRaQpqFzmEkO7pyP0TET8Kayuv5bVX9lA7IUcaKf3YVuOuG/9pO6vvTKHR+yw8JYBgfTxZF+7VDxup7TvhsqfGnWOpwZos+ygF1cWijKSKUhVnc6LE0O2+Q/UtwVEsSwKN3y0uqQcGltMXzIhqqHI2Oq9tceAmRsg2HVZShqdpHM5DpmOCJb8IUfW9PPkRC+ZrMiG+JWKaOAsIPmjt3ROojUXAI382A+D7zO/LeM20h4hDVamrfqqENE4/Prv4O7vDKO7Od+NotLzW/qJ4e37qtC8ipC5YAAqMq8R5zUNPEXSBkom3SW2dMiettx6ZSt4YEnvcoArU7QTJj3qE3iKXWybO5506yoSPD0mZA2h+b28rWmfGPiyMCb0LtJNZuVMFcjr1ncXWeIV0qQp7JWB/bMqyDOkMjfML9dbZFM6Mw9e9UeY69Wa93ngZY4ojCNkbaFj65A+Q5mjJb4WVGjHYAb7O9QNcv65LxAsdSetO6AzH0wTIiIl9Qu7qPwgc7fUUN2C4sDHNdii2fXVn4/xd95nVTFA92ohaS/b/gNhh6GUUxNlXPCVTddqYjav3/Ep7IT3L0VvY0G/twy0OQwD99p7vwkgCKKV9h4S1T71WeMRsXaqfm9sJ2oaVXEzcQSyhewyJ