name: 'Release'
on:
  push:
      tags:
        - v* # Run only on version tags
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Run Kubeseal
        uses: ./.github/actions/kubeseal
        with:
          name: grafana-admin
          namespace: monitoring
          key: password
          value: ${{ secrets.GrafanaAdminPassword }}
          cert: ${{ secrets.SecretSigningCertBase64 }}
          output: grafana/admin-secret.yaml
      - name: 'Checkout deploys'
        uses: actions/checkout@master
        with:
          ref: deploy
          path: deploy
      - name: Update deploy content
        run: | 
            cd deploy
            rm -rf *
            cp -ra ../grafana .
            cp -ra ../jaeger .
            cp -ra ../prometheus .
            cp -a ../kustomization.yaml .
            cp -a ../namespace.yaml .
      - name: Commit
        run: |
            cd deploy
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git add -A
            git commit -m "${{ steps.tagName.outputs.tag }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: deploy